#!/bin/sh
export LANG=en_US.UTF-8
if which ruby >/dev/null && which gem >/dev/null; then
	PATH="$(ruby -rubygems -e 'puts Gem.user_dir')/bin:$PATH"
fi
gem install --user-install cocoapods
cd $1
pod install
